### ISSUE TITLE
第一步上传视频错误

### ISSUE THREAD

**Issue by anna123123123-creator** [xingxing2233/Digital-human-generation#1]
![photo_2024-09-21_21-52-44](https://github.com/user-attachments/assets/cbbeb714-fef0-43de-bfe3-63ed69e08aa2)

使用python3.10.6提示
SSL 模块缺失，搞了几次也没用
![photo_2024-09-21_22-15-57](https://github.com/user-attachments/assets/7b01ba21-8712-4013-93d5-37618d40df05)

**Comment by xingxing2233** [comment]
是安装不上吗？可以试试pip install beautifulsoup4==4.11.1 -i https://mirrors.aliyun.com/pypi/simple/

**Comment by liancheng-zcy** [comment]
![image](https://github.com/user-attachments/assets/de897e8c-44c2-4bd2-bce5-20cc9758b174)
小白请教，全局cuda等环境正常，虚拟环境里也装了，就是没cuda

**Comment by xingxing2233** [comment]
遇到这样的情况请检查一下虚拟环境里面的torch版本是否是支持cuda的版本比如pip install torch==2.1.2 --index-url https://download.pytorch.org/whl/cu118
